# Configuração da Base de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/parking
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-stacktrace=never
spring.web.error.include-path=never

# Configuração do Swagger / SpringDoc
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.show-actuator=true
